In [1]:
import os

os.chdir("..")

current_directory = os.getcwd()
print("Current Working Directory:", current_directory)

Current Working Directory: c:\Users\max-s\Desktop\Uni\Master\Masterthesis\Code\git\overparametrized_dnn


In [6]:
from data.data_generator import get_data, preprocess
from src.my_dnn import create_dnn
from sklearn.model_selection import train_test_split
import numpy as np
import keras
import keras_tuner as kt
import tensorflow as tf

In [7]:
print(tf.__version__)
print(keras.__version__)
print(kt.__version__)
print(np.__version__)
print("GPU is", "available" if tf.config.list_physical_devices("GPU") else "NOT AVAILABLE")

2.15.0
2.15.0
1.4.7
1.26.4
GPU is NOT AVAILABLE


In [ ]:
%tensorboard --logdir logs

In [10]:
def regression_func(x):
    return np.exp(np.linalg.norm(x, axis=1))

input_dim = 7

x, y = get_data(regression_func, x_dim=input_dim, num_samples=100, sigma=0.05)
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2)

train_data = preprocess(x_train, y_train, batch_size=80, training=True)
val_data = preprocess(x_val, y_val, batch_size=20, training=False)

In [12]:
def model_builder(hp):
    hp_units = hp.Int("units", min_value=10, max_value=40, step=10)
    hp_layers = hp.Int("layers", min_value=5, max_value=20, step=5)
    hp_nets = hp.Int("networks", min_value=80, max_value=6 * 80, step=80)
    hp_beta = hp.Float('beta', min_value=20, max_value=80)
    hp_gamma = hp.Float('gamma', min_value=30, max_value=80)
    hp_learning_rate = hp.Float(
        "learning_rate", min_value=np.exp(-16), max_value=np.exp(-14), sampling="log"
    )

    # Hier nutzen Sie Ihre angepasste `create_dnn` Funktion mit den hp-Argumenten
    model = create_dnn(
        train_shape=x_train.shape,  # Beispielwerte
        num_networks=hp_nets,
        num_layers=hp_layers,
        num_neurons=hp_units,
        beta=hp_beta,
        gamma=hp_gamma,
        delta=1,
    )

    optimizer = keras.optimizers.SGD(learning_rate=hp_learning_rate)

    model.compile(
        optimizer=optimizer, loss="mean_squared_error", metrics=["mean_squared_error"]
    )

    return model

In [ ]:
tuner = kt.RandomSearch(
    model_builder,
    objective='val_loss',
    max_trials=20,
    executions_per_trial=2,
    directory='my_dir',
    project_name='rs_tuning'
)

# Starten des Tuning-Prozesses
tuner.search(x_train, y_train, epochs=250, validation_data=(x_val, y_val))

# Abrufen der besten Hyperparameter
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

In [9]:
print(f"""
Die besten Hyperparameter sind:
- Anzahl der Netzwerke: {best_hps.get('networks')}
- Anzahl der Schichten: {best_hps.get('layers')}
- Anzahl der Neuronen: {best_hps.get('units')}
- Delta: {best_hps.get('learning_rate')}
""")


Die besten Hyperparameter sind:
- Anzahl der Netzwerke: 160
- Anzahl der Schichten: 10
- Anzahl der Neuronen: 20
- Delta: 4.156935364128902e-07



In [4]:
def train_and_evaluate_dnn(model, train_data, test_data, epochs=75):
    """
    Trains the model on the given data and evaluates its performance.
    """
    model.fit(train_data, epochs=epochs, verbose=0)
    mse, mae = model.evaluate(test_data, verbose=0)
    return mse, mae

In [5]:
mses = []  # Initialize empty list to store MSEs
maes = []  # Initialize empty list to store MAEs
for _ in range(1):
    x_train, y_train = get_data(
        regression_func, x_dim=input_dim, num_samples=100, sigma=0.05
    )
    x_test, y_test = get_data(
        regression_func, x_dim=input_dim, num_samples=10**5, sigma=0.05
    )

    # Preprocess data
    train_data = preprocess(x_train, y_train, batch_size=100, training=True)
    test_data = preprocess(x_test, y_test, batch_size=100, training=False)

    model = create_dnn(
        train_shape=x_train.shape,  # Beispielwerte
        num_networks=160,
        num_layers=10,
        num_neurons=20,
        beta=80,
        gamma=80,
        delta=1,
    )

    optimizer = keras.optimizers.SGD(learning_rate=np.exp(-15))

    model.compile(
        optimizer=optimizer, loss="mean_squared_error", metrics=["mean_squared_error"]
    )
    mse, mae = train_and_evaluate_dnn(model, train_data, test_data, epochs=500)
    mses.append(mse)
    maes.append(mae)

NotImplementedError: in user code:

    File "c:\Users\max-s\Desktop\Uni\Master\Masterthesis\Code\git\overparametrized_dnn\src\my_dnn.py", line 176, in train_step  *
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))
    File "c:\Users\max-s\anaconda3\envs\py4ds\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 269, in apply_gradients  **
        self.apply(grads, trainable_variables)
    File "c:\Users\max-s\anaconda3\envs\py4ds\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 334, in apply
        variable.assign(variable.constraint(variable))
    File "c:\Users\max-s\Desktop\Uni\Master\Masterthesis\Code\git\overparametrized_dnn\src\my_dnn.py", line 65, in __call__
        return self.apply_l1_projection(w)
    File "c:\Users\max-s\anaconda3\envs\py4ds\Lib\site-packages\tensorflow\core\function\polymorphism\function_type.py", line 583, in canonicalize_to_monomorphic
        _make_validated_mono_param(name, arg, poly_parameter.kind,
    File "c:\Users\max-s\anaconda3\envs\py4ds\Lib\site-packages\tensorflow\core\function\polymorphism\function_type.py", line 522, in _make_validated_mono_param
        mono_type = trace_type.from_value(value, type_context)
    File "c:\Users\max-s\anaconda3\envs\py4ds\Lib\site-packages\tensorflow\core\function\trace_type\trace_type_builder.py", line 185, in from_value
        ndarray = value.__array__()
    File "c:\Users\max-s\anaconda3\envs\py4ds\Lib\site-packages\keras\src\backend\common\variables.py", line 198, in __array__
        return np.asarray(self.value.__array__(dtype))

    NotImplementedError: numpy() is only available when eager execution is enabled.


In [11]:
print(mses)

[0.95123291015625]


In [11]:
model = create_dnn(
        train_shape=x_train.shape,  # Beispielwerte
        num_networks=160,
        num_layers=10,
        num_neurons=20,
        beta=80,
        gamma=80,
        delta=1,
    )

optimizer = keras.optimizers.SGD(learning_rate=np.exp(-14))

model.compile(
    optimizer=optimizer, loss="mean_squared_error", metrics=["mean_squared_error"]
)

In [10]:
model.fit(train_data, epochs=500, validation_data=val_data)

Epoch 1/500
2/2 [==============================] - 855s 58s/step - loss: 13.4205 - val_loss: 1.8008 - val_mean_squared_error: 1.8008
Epoch 2/500
2/2 [==============================] - 1s 368ms/step - loss: 1.8321 - val_loss: 1.8104 - val_mean_squared_error: 1.8104
Epoch 3/500
2/2 [==============================] - 1s 367ms/step - loss: 1.8741 - val_loss: 1.7685 - val_mean_squared_error: 1.7685
Epoch 4/500
2/2 [==============================] - 1s 379ms/step - loss: 1.8196 - val_loss: 1.7667 - val_mean_squared_error: 1.7667
Epoch 5/500
2/2 [==============================] - 1s 366ms/step - loss: 1.7788 - val_loss: 1.8199 - val_mean_squared_error: 1.8199
Epoch 6/500
2/2 [==============================] - 1s 401ms/step - loss: 1.7572 - val_loss: 1.7835 - val_mean_squared_error: 1.7835
Epoch 7/500
2/2 [==============================] - 1s 379ms/step - loss: 1.7855 - val_loss: 1.7095 - val_mean_squared_error: 1.7095
Epoch 8/500
2/2 [==============================] - 1s 397ms/step - loss: 1.

In [11]:
x_val, y_val = get_data(m1, x_dim=m1.expected_dim, num_samples=10**5)
validation_data = preprocess(x_val, y_val, training=False)

model.evaluate(validation_data)

1563/1563 [==============================] - 26s 17ms/step - loss: 0.0071 - mean_squared_error: 0.0071


[0.007052791304886341, 0.007052791304886341]

In [13]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '0'

In [53]:

def apply_l1_projection(self, w):
    if tf.norm(w, ord=1) <= self:
        return w
    # Apply L1-projection on weight vector w
    abs_w = tf.abs(w)

    # Compute cumulative sum of the sorted absolute weights
    u = tf.sort(abs_w, direction="DESCENDING", axis=0)
    svp = tf.cumsum(u, axis=0) - self
    print(u.numpy())
    print(svp)

    # Find the position where the condition is violated for the first time
    ratio = tf.math.divide(svp, tf.constant(tf.range(1, tf.size(u) + 1, dtype=tf.float32), shape=tf.shape(u)))
    print(ratio.numpy())

    # Compute the threshold value
    theta = tf.reduce_max(tf.maximum(ratio, 0.0), axis=0)
    print(theta.numpy())

    return tf.math.sign(w) * tf.maximum(abs_w - theta, 0)

In [54]:
w = tf.Variable(tf.ones(shape=(11, 1)), dtype=tf.float32)
apply_l1_projection(7.0, w)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
tf.Tensor(
[[-6.]
 [-5.]
 [-4.]
 [-3.]
 [-2.]
 [-1.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]], shape=(11, 1), dtype=float32)
[[-6.        ]
 [-2.5       ]
 [-1.3333334 ]
 [-0.75      ]
 [-0.4       ]
 [-0.16666667]
 [ 0.        ]
 [ 0.125     ]
 [ 0.22222222]
 [ 0.3       ]
 [ 0.36363637]]
[0.36363637]


<tf.Tensor: shape=(11, 1), dtype=float32, numpy=
array([[0.6363636],
       [0.6363636],
       [0.6363636],
       [0.6363636],
       [0.6363636],
       [0.6363636],
       [0.6363636],
       [0.6363636],
       [0.6363636],
       [0.6363636],
       [0.6363636]], dtype=float32)>

In [15]:
def test_norm_l1(model):
    # Test if L1 projection of last layer worked
    weights = tf.reshape(model.trainable_variables[-1], [-1])
    norm = tf.norm(weights, ord=1)
    print(f"norm: {norm}, gamma: {model.gamma}")


def test_norm_l2(model):
    # Test if L2 projection of inner weights worked
    current_weights = tf.concat(
        [tf.reshape(v, [-1]) for v in model.trainable_weights[:-1]], axis=0
    )
    sub_nets_init_weights = model.sub_nets_init_weights
    diff = sub_nets_init_weights - current_weights
    norm = tf.norm(diff)
    print(f"norm: {norm}, delta: {model.delta}")

In [16]:
test_norm_l1(model)
test_norm_l2(model)

norm: 0.7622666954994202, gamma: 10
norm: 0.0030101335141807795, delta: 1.0
